Update Buildspec.yml

diff --git a/.github/workflows/Buildspec.yml b/.github/workflows/Buildspec.yml
--- a/.github/workflows/Buildspec.yml
+++ b/.github/workflows/Buildspec.yml
@@ -30,25 +30,16 @@ phases:
 
   post_build:
     commands:
-      - echo "--- Uploading WAR to S3 ---"
-      - |
-        if [ -f "target/Ecomm.war" ]; then
-          echo "Attempting upload to s3://$S3_BUCKET/Ecomm.war"
-          aws s3 cp target/Ecomm.war "s3://$S3_BUCKET/Ecomm.war" --debug || {
-            echo "Failed to upload to S3";
-            echo "Possible causes:";
-            echo "1. S3_BUCKET not set or incorrect";
-            echo "2. Missing IAM permissions";
-            echo "3. File doesn't exist";
-            exit 1;
-          }
-        else
-          echo "Error: target/Ecomm.war not found!"
-          exit 1
-        fi
+      - echo "--- Uploading to S3 ---"
+      - echo "Uploading target/Ecomm.war to s3://${S3_BUCKET}/Ecomm.war"
+      - aws s3 ls "s3://${S3_BUCKET}/" || echo "WARNING: Cannot list bucket contents - may not have permissions"
+      - aws s3 cp target/Ecomm.war "s3://${S3_BUCKET}/Ecomm.war"
+      
       - echo "--- Deploying to Tomcat ---"
-      - curl -f -u "$TOMCAT_USERNAME:$TOMCAT_PASSWORD" -T target/Ecomm.war "http://3.109.208.89:8080/manager/text/deploy?path=/Ecomm&update=true"
+      - curl -v -u "${TOMCAT_USERNAME}:${TOMCAT_PASSWORD}" -T target/Ecomm.war "http://3.109.208.89:8080/manager/text/deploy?path=/Ecomm&update=true"
 
 artifacts:
   files:
     - target/Ecomm.war
+  name: ecom-artifact
+    
